### ISSUE TITLE
Remove fields from create Event screen

### ISSUE THREAD

**Issue by galtibi22** [mishkakipi/CalManAfeka#4]
@mishkakipi 
please remove the next fields:
Event Id - you need to send me calendar events without event ID
Modify Type - I dont know what is is

![image](https://user-images.githubusercontent.com/11310460/28869134-7467f602-7784-11e7-9d59-a1c05b5cc9d0.png)

**Comment by mishkakipi** [comment]
Modify type is what the nature of change: create update delete or delete all
Event ID is the ID of the event in calendar

**Comment by galtibi22** [comment]
ok, I close the it
